Resolve the PGW issue of PDP on swatch change
cloudinary/cloudinary_sfcc_pwa-kit pull request #3
Opened 2024-07-08 12:02 UTC by asad-rafter

2024-07-08 12:43 UTC, yuval-cloudinary requested changes

2024-07-08 12:43 UTC, yuval-cloudinary commented on Cloudinary-pwa-kit/packages/pwa-cloudinary/app/components/cloudinary-widgets/index.jsx
> +                window.cldGallery = window.cloudinary.galleryWidget(galleryOptions)
Please create a new gallery only if it doesn't exist. Otherwise, we're risking memory leaks or other hard-to-debug issues

2024-07-08 12:43 UTC, yuval-cloudinary commented on Cloudinary-pwa-kit/packages/pwa-cloudinary/app/components/cloudinary-widgets/index.jsx
> +                cldGallery.update(galleryOptions)
Please update the gallery only when needed, e.g. when changing the existing gallery. This would perform faster for the users

2024-07-08 13:49 UTC, asad-rafter commented on Cloudinary-pwa-kit/packages/pwa-cloudinary/app/components/cloudinary-widgets/index.jsx
> +                cldGallery.update(galleryOptions)
If I add condition this way
if (window.cldGallery) {
                    cldGallery.update(galleryOptions)
                } else {
                    window.cldGallery = window.cloudinary.galleryWidget(galleryOptions)
                }
it takes a delay, and load the previous image for milliseconds first and then updates the gallery with new image when we change the PDP, do you want me to push the code so you can validate?

2024-07-15 04:53 UTC, yuval-cloudinary commented
This is resolved by other PRs. Closing without merging

2024-07-15 04:53 UTC, closed without merging