added imageSrcset.js
cloudinary/cloudinary_sfcc_pwa-kit pull request #5
Opened 2024-07-15 08:01 UTC by asad-rafter

2024-07-15 08:02 UTC, asad-rafter commented
@yuval-cloudinary, apologies, this file was missing in the previous PR. I just added please review

2024-07-15 08:30 UTC, asad-rafter commented on Cloudinary-pwa-kit/packages/pwa-cloudinary/overrides/app/components/footer/index.jsx
@yuval-cloudinary, we were having issue when we directly access "cloudinary" object in <Helmet> tag, that's the reason we had to move it to outside of <Helmet> tag, it works fine this way

2024-07-15 08:43 UTC, yuval-cloudinary approved these changes

2024-07-15 08:43 UTC, yuval-cloudinary commented on Cloudinary-pwa-kit/packages/pwa-cloudinary/overrides/app/components/footer/index.jsx
cool

2024-07-15 08:45 UTC, yuval-cloudinary requested changes

2024-07-15 08:45 UTC, yuval-cloudinary commented on Cloudinary-pwa-kit/packages/pwa-cloudinary/app/utils/imageSrcset.js
> +    let splits = srcset.split(' ')
please use const

2024-07-15 08:45 UTC, yuval-cloudinary commented on Cloudinary-pwa-kit/packages/pwa-cloudinary/app/utils/imageSrcset.js
> +    let newSrcset = splits.map((split) => {
please use const

2024-07-15 11:29 UTC, yuval-cloudinary approved these changes

2024-07-15 11:29 UTC, merged

2024-07-24 07:45 UTC, yuval-cloudinary reviewed
Approved